package deleteservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DeleteFileService service = new DeleteFileService();
 * DeleteFileDelegate portType = service.getDeleteFilePort1();
 * portType.delete(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DeleteFileService", targetNamespace = "http://logic.com/", wsdlLocation = "http://localhost:9999/IdentityBasedStorage/DeleteFilePort1?wsdl")
public class DeleteFileService extends Service {

	//private final static URL DELETEFILESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(deleteservice.DeleteFileService.class.getName());

//	static {
//		URL url = null;
//		try {
//			URL baseUrl;
//			baseUrl = deleteservice.DeleteFileService.class.getResource(".");
//			url = new URL(baseUrl,
//					"http://localhost:9999/IdentityBasedStorage/DeleteFilePort1?wsdl");
//		} catch (MalformedURLException e) {
//			logger
//					.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/IdentityBasedStorage/DeleteFilePort1?wsdl', retrying as a local file");
//			logger.warning(e.getMessage());
//		}
//		DELETEFILESERVICE_WSDL_LOCATION = url;
//	}

	public DeleteFileService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DeleteFileService(URL DELETEFILESERVICE_WSDL_LOCATION) {
		super(DELETEFILESERVICE_WSDL_LOCATION, new QName("http://logic.com/",
				"DeleteFileService"));
	}

	/**
	 * 
	 * @return returns DeleteFileDelegate
	 */
	@WebEndpoint(name = "DeleteFilePort1")
	public DeleteFileDelegate getDeleteFilePort1() {
		return super.getPort(new QName("http://logic.com/", "DeleteFilePort1"),
				DeleteFileDelegate.class);
	}

}
