package deleteservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DeleteFileDelegate", targetNamespace = "http://logic.com/")
public interface DeleteFileDelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://logic.com/", className = "deleteservice.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://logic.com/", className = "deleteservice.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteDir", targetNamespace = "http://logic.com/", className = "deleteservice.DeleteDir")
	@ResponseWrapper(localName = "deleteDirResponse", targetNamespace = "http://logic.com/", className = "deleteservice.DeleteDirResponse")
	public boolean deleteDir(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
