package service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * FileUploadService1 service = new FileUploadService1();
 * FileUploadDelegate portType = service.getFileUploadPort();
 * portType.saveFile(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "FileUploadService1", targetNamespace = "http://logic.com/", wsdlLocation = "http://localhost:8888/IdentityBasedStorage/FileUploadPort?wsdl")
public class FileUploadService1 extends Service {

	//private final static URL FILEUPLOADSERVICE1_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(service.FileUploadService1.class.getName());

//	static {
//		URL url = null;
//		try {
//			URL baseUrl;
//			baseUrl = service.FileUploadService1.class.getResource(".");
//			url = new URL(baseUrl,
//					"http://localhost:8888/IdentityBasedStorage/FileUploadPort?wsdl");
//		} catch (MalformedURLException e) {
//			logger
//					.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/IdentityBasedStorage/FileUploadPort?wsdl', retrying as a local file");
//			logger.warning(e.getMessage());
//		}
//		FILEUPLOADSERVICE1_WSDL_LOCATION = url;
//	}

	public FileUploadService1(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FileUploadService1(URL FILEUPLOADSERVICE1_WSDL_LOCATION) {
		super(FILEUPLOADSERVICE1_WSDL_LOCATION, new QName("http://logic.com/",
				"FileUploadService1"));
	}

	/**
	 * 
	 * @return returns FileUploadDelegate
	 */
	@WebEndpoint(name = "FileUploadPort")
	public FileUploadDelegate getFileUploadPort() {
		return super.getPort(new QName("http://logic.com/", "FileUploadPort"),
				FileUploadDelegate.class);
	}

}
