package auditservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PublicAuditService service = new PublicAuditService();
 * PublicAuditDelegate portType = service.getPublicAuditPort();
 * portType.startAudit(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PublicAuditService", targetNamespace = "http://logic.com/", wsdlLocation = "http://localhost:8888/IdentityBasedStorage/PublicAuditPort?wsdl")
public class PublicAuditService extends Service {

	//private final static URL PUBLICAUDITSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(auditservice.PublicAuditService.class.getName());

//	static {
//		URL url = null;
//		try {
//			URL baseUrl;
//			baseUrl = auditservice.PublicAuditService.class.getResource(".");
//			url = new URL(baseUrl,
//					"http://localhost:8888/IdentityBasedStorage/PublicAuditPort?wsdl");
//		} catch (MalformedURLException e) {
//			logger
//					.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/IdentityBasedStorage/PublicAuditPort?wsdl', retrying as a local file");
//			logger.warning(e.getMessage());
//		}
//		PUBLICAUDITSERVICE_WSDL_LOCATION = url;
//	}

	public PublicAuditService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PublicAuditService(URL PUBLICAUDITSERVICE_WSDL_LOCATION) {
		super(PUBLICAUDITSERVICE_WSDL_LOCATION, new QName("http://logic.com/",
				"PublicAuditService"));
	}

	/**
	 * 
	 * @return returns PublicAuditDelegate
	 */
	@WebEndpoint(name = "PublicAuditPort")
	public PublicAuditDelegate getPublicAuditPort() {
		return super.getPort(new QName("http://logic.com/", "PublicAuditPort"),
				PublicAuditDelegate.class);
	}

}
